# -*- coding: utf-8 -*-
import sys

import numpy as np
import torch
# Form implementation generated from reading ui file 'GUI_style2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog, QWidget


class Ui_MainWindow(QWidget):
    def __init__(self,mainWindow,application) -> None:
        super().__init__()

        '''初始化参数'''
        self.app = application

        '''引入yolov5训练模型'''
        self.model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

        '''加载UI到窗口'''
        self.setupUi(mainWindow)

        '''按钮监听'''
        self.select_img_btn.clicked.connect(self.select_image_btn)
        self.detect_img_btn.clicked.connect(self.delect_image_btn)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 634)
        MainWindow.setStyleSheet("")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.detect_frame = QtWidgets.QFrame(self.centralwidget)
        self.detect_frame.setGeometry(QtCore.QRect(10, 10, 681, 431))
        self.detect_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.detect_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detect_frame.setObjectName("detect_frame")
        self.detect_window = QtWidgets.QLabel(self.detect_frame)
        self.detect_window.setGeometry(QtCore.QRect(20, 40, 640, 371))
        self.detect_window.setStyleSheet("QLabel{\n"
                                         "    background-color: rgb(0, 0, 0);\n"
                                         "}")
        self.detect_window.setFrameShape(QtWidgets.QFrame.Box)
        self.detect_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detect_window.setText("")
        self.detect_window.setTextFormat(QtCore.Qt.AutoText)
        self.detect_window.setScaledContents(False)
        self.detect_window.setAlignment(QtCore.Qt.AlignCenter)
        self.detect_window.setObjectName("detect_window")
        self.label = QtWidgets.QLabel(self.detect_frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.img_frame = QtWidgets.QFrame(self.centralwidget)
        self.img_frame.setGeometry(QtCore.QRect(700, 40, 231, 171))
        self.img_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.img_frame.setObjectName("img_frame")
        self.select_img_btn = QtWidgets.QPushButton(self.img_frame)
        self.select_img_btn.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.select_img_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_img_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.select_img_btn.setAutoFillBackground(False)
        self.select_img_btn.setStyleSheet("QPushButton {\n"
                                          "    background-color: #ffffff;\n"
                                          "    border: 1px solid rgb(76, 76, 76);\n"
                                          "    padding: 10px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: #ecf5ff;\n"
                                          "    color: #409eff;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed, QPushButton:checked {\n"
                                          "    border: 1px solid #3a8ee6;\n"
                                          "    color: #409eff;\n"
                                          "}\n"
                                          "\n"
                                          "#button3 {\n"
                                          "    border-radius: 20px;\n"
                                          "}")
        self.select_img_btn.setAutoDefault(False)
        self.select_img_btn.setDefault(False)
        self.select_img_btn.setObjectName("select_img_btn")
        self.detect_img_btn = QtWidgets.QPushButton(self.img_frame)
        self.detect_img_btn.setGeometry(QtCore.QRect(30, 100, 161, 41))
        self.detect_img_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detect_img_btn.setStyleSheet("QPushButton {\n"
                                          "    background-color: #ffffff;\n"
                                          "    border: 1px solid rgb(76, 76, 76);\n"
                                          "    padding: 10px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: #ecf5ff;\n"
                                          "    color: #409eff;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed, QPushButton:checked {\n"
                                          "    border: 1px solid #3a8ee6;\n"
                                          "    color: #409eff;\n"
                                          "}\n"
                                          "\n"
                                          "#button3 {\n"
                                          "    border-radius: 20px;\n"
                                          "}")
        self.detect_img_btn.setAutoDefault(False)
        self.detect_img_btn.setDefault(False)
        self.detect_img_btn.setObjectName("detect_img_btn")
        self.camera_frame = QtWidgets.QFrame(self.centralwidget)
        self.camera_frame.setGeometry(QtCore.QRect(700, 260, 231, 181))
        self.camera_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_frame.setObjectName("camera_frame")
        self.start_camera_btn = QtWidgets.QPushButton(self.camera_frame)
        self.start_camera_btn.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.start_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_camera_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.start_camera_btn.setAutoFillBackground(False)
        self.start_camera_btn.setStyleSheet("QPushButton {\n"
                                            "    background-color: #ffffff;\n"
                                            "    border: 1px solid rgb(76, 76, 76);\n"
                                            "    padding: 10px;\n"
                                            "    border-radius: 5px;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color: #ecf5ff;\n"
                                            "    color: #409eff;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed, QPushButton:checked {\n"
                                            "    border: 1px solid #3a8ee6;\n"
                                            "    color: #409eff;\n"
                                            "}\n"
                                            "\n"
                                            "#button3 {\n"
                                            "    border-radius: 20px;\n"
                                            "}")

        self.start_camera_btn.setAutoDefault(False)
        self.start_camera_btn.setDefault(False)
        self.start_camera_btn.setObjectName("start_camera_btn")
        self.detect_camera_btn = QtWidgets.QPushButton(self.camera_frame)
        self.detect_camera_btn.setGeometry(QtCore.QRect(30, 110, 161, 41))
        self.detect_camera_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.detect_camera_btn.setStyleSheet("QPushButton {\n"
                                             "    background-color: #ffffff;\n"
                                             "    border: 1px solid rgb(76, 76, 76);\n"
                                             "    padding: 10px;\n"
                                             "    border-radius: 5px;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: #ecf5ff;\n"
                                             "    color: #409eff;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed, QPushButton:checked {\n"
                                             "    border: 1px solid #3a8ee6;\n"
                                             "    color: #409eff;\n"
                                             "}\n"
                                             "\n"
                                             "#button3 {\n"
                                             "    border-radius: 20px;\n"
                                             "}")
        self.detect_camera_btn.setAutoDefault(False)
        self.detect_camera_btn.setDefault(False)
        self.detect_camera_btn.setObjectName("detect_camera_btn")
        self.detect_print_title = QtWidgets.QLabel(self.centralwidget)
        self.detect_print_title.setGeometry(QtCore.QRect(10, 450, 72, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.detect_print_title.setFont(font)
        self.detect_print_title.setObjectName("detect_print_title")
        self.detect_print_text = QtWidgets.QLabel(self.centralwidget)
        self.detect_print_text.setGeometry(QtCore.QRect(20, 490, 671, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.detect_print_text.setFont(font)
        self.detect_print_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.detect_print_text.setObjectName("detect_print_text")
        self.detect_img_title = QtWidgets.QLabel(self.centralwidget)
        self.detect_img_title.setGeometry(QtCore.QRect(700, 0, 72, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.detect_img_title.setFont(font)
        self.detect_img_title.setObjectName("detect_img_title")
        self.detect_camera_title = QtWidgets.QLabel(self.centralwidget)
        self.detect_camera_title.setGeometry(QtCore.QRect(700, 220, 72, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.detect_camera_title.setFont(font)
        self.detect_camera_title.setObjectName("detect_camera_title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 949, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ASL_Detection - v1.0"))
        self.label.setText(_translate("MainWindow", "检测窗口:"))
        self.select_img_btn.setText(_translate("MainWindow", "选择图片"))
        self.detect_img_btn.setText(_translate("MainWindow", "检测"))
        self.start_camera_btn.setText(_translate("MainWindow", "开启摄像头"))
        self.detect_camera_btn.setText(_translate("MainWindow", "开启检测"))
        self.detect_print_title.setText(_translate("MainWindow", "检测信息："))
        self.detect_print_text.setText(_translate("MainWindow", ""))
        self.detect_img_title.setText(_translate("MainWindow", "图片检测："))
        self.detect_camera_title.setText(_translate("MainWindow", "实时检测："))
        self.menu.setTitle(_translate("MainWindow", "关于"))

    '''选择本地图片'''
    def select_image_btn(self):
        self.image, _ = QFileDialog.getOpenFileName(self, '打开文件', './', '图像文件(*.jpg *.png)')

        if len(self.image) != None :
            self.detect_window.setPixmap(QPixmap(self.image))

    '''检测本地图片'''
    def delect_image_btn(self):
        if self.image != None :
            results = self.model(self.image)

            img = np.squeeze(results.render())
            showImage = QImage(img.data, img.shape[1], img.shape[0], QImage.Format_RGB888)
            self.detect_window.setPixmap(QPixmap.fromImage(showImage))

if __name__ == '__main__':
    app = QApplication(sys.argv)

    MainWindow = QMainWindow()
    ui = Ui_MainWindow(MainWindow,app)
    MainWindow.show()

    sys.exit(app.exec_())
